### ISSUE TITLE
Excellent program！

### ISSUE THREAD

**Issue by zwlshine** [Lw-Cui/Drawing-board#1]
It's a very good projects, especially for the plugin usage.

**Comment by Lw-Cui** [comment]
Thanks but this section is for for issues report, not general comment:)

**Comment by zwlshine** [comment]
@Lw-Cui  Hello，how to create a project like circle in your project in Qt5, maybe like File->New..Project->Library->C++Library->Type, so I want to know the circle project in yours belong to what kind and type project, how to create in Qt5? Thank you!

**Comment by Lw-Cui** [comment]
Hi zwlshine
[Adding Libraries to Projects](http://doc.qt.io/qtcreator/creator-project-qmake-libraries.html) is for your reference. 
Since they are dynamic libraries I guess you can create it directly by writing .pro yourself.
